services:
  httpd:
    build:
      context: ./versions/${HTTPDVERSION}
    image: "${PROJECT_NAME}-${HTTPDVERSION}"
    container_name: "${PROJECT_NAME}-${HTTPDVERSION}"
    ports:
      - "${HOST_UNSECURE_PORT}:8080"
      - "${HOST_SECURE_PORT}:443"
    environment:
      - HTTPD_PREFIX=/usr/local/apache2
    volumes:
      - ${DOCUMENT_ROOT}:/usr/local/apache2/htdocs:ro
      - ${SSL_CERT_DIR}:/etc/ssl/certs
      - ${SSL_INTERNAL_CERT_DIR}:/usr/local/share/ca-certificates
    command: sh ./myscript.sh 
  db:
    image:  "${PROJECT_NAME}-${MYSQLVERSION}"
    container_name: "${PROJECT_NAME}-${MYSQLVERSION}"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: mysqld
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
  php-fpm:
    image: "${PROJECT_NAME}-${PHP-FPMVERSION}"
    pull_policy: never                   # Require a custom image built first, step 2
    container_name: my-php-fpm
    restart: unless-stopped
    working_dir: /var/www/htm
    ports:
      - "9000:9000"
    environment:
      - PHP_PREFIX=/opt/php-8.5
    volumes:
      - /home/app/php:/var/www/html:ro
