services:
  httpd:
    build:
      context: ./versions/${HTTPDVERSION}
      args:
        - CERT_SUBJ=${CERT_SUBJ}
        - SERVER_NAME=${SERVER_NAME}
        - SERVER_ADMIN=${SERVER_ADMIN}
    image: "${PROJECT_NAME}-${HTTPDVERSION}"
    container_name: "${PROJECT_NAME}-httpd"
    restart: always
    ports:
      - "${HOST_UNSECURE_PORT}:8080"
      - "${HOST_SECURE_PORT}:443"
    environment:
      - HTTPD_PREFIX=/usr/local/apache2
      - HTTPD_VERSION=2.4.68
      - LD_LIBRARY_PATH=/usr/local/apr/lib:/usr/local/apr-util/lib
      - PATH=/usr/local/apache2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
    volumes:
      - ${DOCUMENT_ROOT}:/usr/local/apache2/htdocs:ro
      - ${HTTPD_CERT_DIR}:/usr/local/apache2/conf/certs
    depends_on:
      - php-fpm
  mysqld:
    build:
      context: ./versions/${MYSQLVERSION}
      args:
        - MYCNF=${MYCNF}
    image:  "${PROJECT_NAME}-${MYSQLVERSION}"
    container_name: "${PROJECT_NAME}-mysql"
    user: "${UID}:${GID}"
    restart: always
    ports:
      - "${HOST_MYSQL_PORT}:3306"
      - "${HOST_MYSQLX_PORT}:33060"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_OPTIONS=${MYSQL_OPTIONS}
    command: mysqld
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
      - ${MYSQL_CERT_DIR}:/opt/mysql/certs
  php-fpm:
    build:
      context: ./versions/${PHPVERSION}
    image: "${PROJECT_NAME}-${PHPVERSION}"
    container_name: "${PROJECT_NAME}-php-fpm"
    user: "${UID}:${GID}"
    pull_policy: never                   # Require a custom image built first, step 2
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "${HOST_PHP_PORT}:9000"
    environment:
      - PHP_INI_DIR=/usr/local/etc/php
      - PHP_PREFIX=/opt/php-8.5
    volumes:
      - ${DOCUMENT_ROOT}:/var/www/html:ro
