name: LAMP deploy on remote server via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs on GitHub's cloud runners

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Remote Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to project directory on local machine
            cd /path/to/your/app

            # login to dhi.io
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login dhi.io -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            #echo "${{ secrets.DOCKER_PASSWORD }}" | docker login dhi.io --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            # Pull latest changes from git
            git pull origin main

            # Setup
            sh setup.sh

            # Restart docker compose
            docker compose up -d --build --remove-orphans
