name: LAMP deploy on remote server via SSH

on:
  #push:
  workflow_dispatch: 
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs on GitHub's cloud runners

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Remote Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to project directory on local machine
            cd /path/to/your/app
            
            # Pull latest changes from git
            git pull origin main

            # setup
            sh setup.sh
            
            # Restart docker compose
            docker compose up -d --build --remove-orphans
